# Generated by Django 5.1.6 on 2026-08-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='capability',
            index=models.Index(fields=['is_published', 'order'], name='content_cap_is_publ_d535da_idx'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['is_published', 'order'], name='content_faq_is_publ_789707_idx'),
        ),
        migrations.AddIndex(
            model_name='statistic',
            index=models.Index(fields=['is_published', 'order'], name='content_sta_is_publ_a0b7c1_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['is_published', 'order'], name='content_tea_is_publ_003e0d_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['is_published', 'order'], name='content_tes_is_publ_154443_idx'),
        ),
    ]
