# Generated by Django 5.1.6 on 2026-08-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('name', models.CharField(blank=True, max_length=160, verbose_name='نام')),
                ('language', models.CharField(default='fa', max_length=5, verbose_name='زبان')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تایید')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان لغو')),
            ],
            options={
                'verbose_name': 'مشترک خبرنامه',
                'verbose_name_plural': 'مشترکین خبرنامه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی')),
                ('name', models.CharField(max_length=160, verbose_name='نام')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='تلفن')),
                ('company', models.CharField(blank=True, max_length=160, verbose_name='شرکت')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیام')),
                ('service', models.CharField(blank=True, help_text='مثل web / matlab / comsol / ai', max_length=60, verbose_name='سرویس مورد نظر')),
                ('budget', models.CharField(choices=[('undecided', 'نامشخص'), ('small', 'کمتر از ۵ هزار دلار'), ('medium', '۵ تا ۲۰ هزار دلار'), ('large', '۲۰ تا ۵۰ هزار دلار'), ('enterprise', 'بیش از ۵۰ هزار دلار')], default='undecided', max_length=20, verbose_name='بودجه')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('read', 'خوانده شده'), ('replied', 'پاسخ داده شده'), ('archived', 'بایگانی'), ('spam', 'اسپم')], db_index=True, default='new', max_length=20, verbose_name='وضعیت')),
                ('internal_note', models.TextField(blank=True, verbose_name='یادداشت داخلی')),
                ('language', models.CharField(blank=True, max_length=5, verbose_name='زبان')),
                ('source_page', models.CharField(blank=True, max_length=300, verbose_name='صفحه مبدا')),
                ('ip_hash', models.CharField(blank=True, editable=False, max_length=64, verbose_name='هش آی\u200cپی')),
                ('user_agent', models.CharField(blank=True, editable=False, max_length=300, verbose_name='مرورگر')),
            ],
            options={
                'verbose_name': 'پیام تماس',
                'verbose_name_plural': 'پیام\u200cهای تماس',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='leads_conta_status_13e448_idx')],
            },
        ),
    ]
