# Generated by Django 5.1.6 on 2026-08-17 20:16

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscriber',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='subscriber_email_ci_unique'),
        ),
    ]
