<?php
declare(strict_types=1);

/**
 * UI dictionary for both languages.
 * t('key') resolves the string for the current language (see functions.php).
 */
return [
    'fa' => [
        'lang.name'        => 'فارسی',
        'lang.switch'      => 'EN',

        'nav.home'         => 'خانه',
        'nav.projects'     => 'پروژه‌ها',
        'nav.blog'         => 'بلاگ',
        'nav.about'        => 'درباره ما',
        'nav.contact'      => 'تماس',
        'nav.cta'          => 'شروع یک پروژه',

        'hero.scroll'      => 'اسکرول',
        'hero.ctaPrimary'  => 'مشاهده پروژه‌ها',
        'hero.ctaSecondary'=> 'درخواست همکاری',

        'cap.title'        => 'آنچه می‌سازیم',
        'cap.subtitle'     => 'از نرم‌افزارهای هوشمند تا شبیه‌سازی‌های مهندسی پیشرفته؛ چالش‌های فنی پیچیده را به راه‌حل‌های مهندسی‌شده تبدیل می‌کنیم.',
        'cap.c0.title'     => 'فناوری پایه و مهندسی',
        'cap.c0.desc'      => 'معماری‌های محکم و پایدار با زبان‌ها و فریم‌ورک‌های مدرن از جمله Python، C++، React و OpenCV برای راه‌حل‌های تخصصی.',
        'cap.c0.link'      => 'مشاهده فناوری‌ها',
        'cap.c1.title'     => 'شبیه‌سازی‌های مهندسی',
        'cap.c1.desc'      => 'حل مسائل الکترومغناطیسی، حرارتی و مکانیکی با COMSOL و MATLAB؛ از مدل‌سازی سه‌بعدی تا بهینه‌سازی پارامترها.',
        'cap.c1.link'      => 'پروژه‌های شبیه‌سازی',
        'cap.c2.title'     => 'برنامه‌نویسی و هوش مصنوعی',
        'cap.c2.desc'      => 'پردازش سیگنال، بینایی ماشین و اتوماسیون فرایند با Python و مدل‌های یادگیری عمیق؛ داده خام به تصمیم هوشمند.',
        'cap.c2.link'      => 'پروژه‌های برنامه‌نویسی',
        'cap.c3.title'     => 'طراحی و توسعه وب',
        'cap.c3.desc'      => 'وب‌سایت‌های چندزبانه، داشبورد‌های داده و پنل‌های مدیریت با معماری تمیز، سئوی عمیق و عملکرد بالا.',
        'cap.c3.link'      => 'پروژه‌های وب',

        'home.projects.title'   => 'پروژه‌های منتخب',
        'home.projects.subtitle'=> 'نمونه‌ای از راه‌حل‌های مهندسی، نرم‌افزاری و هوش مصنوعی که توسعه داده‌ایم.',
        'home.projects.viewAll' => 'مشاهده همه پروژه‌ها',
        'home.blog.title'       => 'آخرین مطالب',
        'home.blog.subtitle'    => 'دانش فنی تیم فیزیو‌الکتریک؛ از شبیه‌سازی تا سئوی چندزبانه.',
        'home.blog.viewAll'     => 'همه مطالب',

        'process.title'   => 'فرایند کار ما',
        'process.subtitle'=> 'مسیر پروژه شما از یک ایده تا محصول نهایی، در چهار گام شفاف.',
        'process.s1.t'    => 'بررسی و تحلیل',
        'process.s1.d'    => 'نیازها را دقیق می‌شنویم، مسئله را مدل‌سازی می‌کنیم و دامنهٔ پروژه را مشخص می‌کنیم.',
        'process.s2.t'    => 'طراحی و شبیه‌سازی',
        'process.s2.d'    => 'با مدل‌های دیجیتال، ریسک‌ها را قبل از ساخت حذف می‌کنیم و بهترین معماری را انتخاب می‌کنیم.',
        'process.s3.t'    => 'پیاده‌سازی و تست',
        'process.s3.d'    => 'کدنویسی تمیز، تست‌های خودکار و بازبینی مرحله‌به‌مرحله با شما.',
        'process.s4.t'    => 'تحویل و پشتیبانی',
        'process.s4.d'    => 'مستندسازی کامل، آموزش و پشتیبانی پس از راه‌اندازی.',

        'faq.title'    => 'سوالات پرتکرار',
        'faq.q1'       => 'چطور قیمت‌گذاری انجام می‌شود؟',
        'faq.a1'       => 'قیمت بر اساس دامنه، پیچیدگی فنی و زمان پروژه تعیین می‌شود. بعد از جلسهٔ اولیهٔ رایگان، پیشنهاد فنی-مالی مکتوب دریافت می‌کنید؛ بدون هزینه‌های پنهان.',
        'faq.q2'       => 'آیا پروژه‌های کوچک را هم قبول می‌کنید؟',
        'faq.a2'       => 'بله. از یک اسکریپت تحلیل داده تا یک سامانهٔ کامل، اگر در حوزهٔ تخصص ما باشد با دقت یکسان پیگیری می‌شود.',
        'faq.q3'       => 'مدت زمان تحویل پروژه چقدر است؟',
        'faq.a3'       => 'به دامنهٔ کار بستگی دارد؛ پروژه‌های شبیه‌سازی معمولاً ۲ تا ۶ هفته و پروژه‌های نرم‌افزاری ۴ تا ۱۲ هفته زمان می‌برند. زمان‌بندی دقیق در پیشنهاد فنی مشخص می‌شود.',
        'faq.q4'       => 'آیا قرارداد و محرمانگی (NDA) دارید؟',
        'faq.a4'       => 'بله. همهٔ پروژه‌ها با قرارداد مکتوب و در صورت نیاز با توافق‌نامهٔ محرمانگی (NDA) آغاز می‌شوند.',
        'faq.q5'       => 'پس از تحویل، پشتیبانی دارید؟',
        'faq.a5'       => 'بله. همهٔ تحویل‌ها با مستندسازی فنی و دوره‌ای پشتیبانی رایگان همراه است و طرح‌های پشتیبانی بلندمدت نیز قابل عقد است.',

        'contact.title'      => 'بیایید دربارهٔ پروژه‌تان حرف بزنیم',
        'contact.subtitle'   => 'تلفنی، ایمیلی یا از طریق تلگرام؛ ما معمولاً در کمتر از ۲۴ ساعت پاسخ می‌دهیم.',
        'contact.telegram'   => 'گفتگو در تلگرام',
        'contact.email'      => 'ارسال ایمیل',
        'contact.phone'      => 'تلفن',
        'contact.address'    => 'آدرس',
        'contact.worktime'   => 'شنبه تا چهارشنبه، ۹ تا ۱۷',

        'cta.title'     => 'پروژه‌ای مشابه می‌خواهید؟',
        'cta.subtitle'  => 'با تیم ما تماس بگیرید تا ایدهٔ شما را به یک راه‌حل عملی تبدیل کنیم.',
        'cta.telegram'  => 'سفارش در تلگرام',
        'cta.email'     => 'درخواست از طریق ایمیل',
        'cta.tgMsg'     => 'سلام! پروژه «{title}» را در سایت فیزیو‌الکتریک دیدم و می‌خواهم پروژه‌ای مشابه سفارش دهم.',
        'cta.mailSubj'  => 'درخواست پروژه: {title}',

        'projects.all'         => 'همهٔ پروژه‌ها',
        'projects.title'       => 'پروژه‌ها',
        'projects.subtitle'    => 'نمونه‌های انتخابی از کارهای مهندسی، نرم‌افزاری و وب ما.',
        'projects.view'        => 'مشاهدهٔ پروژه',
        'projects.order'       => 'سفارش پروژه',
        'projects.related'     => 'پروژه‌های مرتبط',
        'projects.category'    => 'دسته‌بندی',
        'projects.tags'        => 'فناوری‌ها',
        'projects.updated'     => 'به‌روزرسانی',
        'projects.notFound'    => 'پروژه‌ای با این مشخصات یافت نشد.',
        'projects.back'        => 'بازگشت',

        'blog.title'        => 'بلاگ',
        'blog.subtitle'     => 'مقالات فنی، آموزش‌ها و تجربه‌های تیم فیزیو‌الکتریک.',
        'blog.readMore'     => 'ادامهٔ مطلب',
        'blog.related'      => 'مطالب مرتبط',
        'blog.share'        => 'اشتراک‌گذاری',
        'blog.back'         => 'بازگشت به بلاگ',
        'blog.minRead'      => 'دقیقه مطالعه',
        'blog.noPosts'      => 'هنوز مطلبی منتشر نشده است.',
        'blog.published'    => 'منتشرشده در',

        'about.title'       => 'دربارهٔ فیزیو‌الکتریک',
        'about.subtitle'    => 'ما یک استودیوی مهندسی-نرم‌افزاری هستیم که فیزیک، ریاضی و کد را در یک تیم جمع کرده است.',
        'about.story.t'     => 'داستان ما',
        'about.story.p1'    => 'فیزیو‌الکتریک از تلاقی دو دنیای مهندسی و برنامه‌نویسی شکل گرفته است. ما باور داریم بهترین راه‌حل‌ها زمانی به‌دست می‌آیند که فیزیک مسئله، ریاضیات مدل و کد پیاده‌سازی از ابتدا با هم فکر کنند.',
        'about.story.p2'    => 'امروز تیم ما در سه محور اصلی کار می‌کند: شبیه‌سازی‌های مهندسی پیشرفته، توسعهٔ نرم‌افزارهای تخصصی و طراحی وب‌سایت‌های مدرن. هر پروژه — بزرگ یا کوچک — با همان دقت و شفافیت پیگیری می‌شود.',
        'about.v1.t'        => 'دقت مهندسی',
        'about.v1.d'        => 'هر عددی که تحویل می‌دهیم از یک مدل معتبر و دادهٔ واقعی به‌دست می‌آید.',
        'about.v2.t'        => 'شفافیت کامل',
        'about.v2.d'        => 'پیشرفت پروژه در هر مرحله قابل سنجش و مستند است؛ بدون سورپرایز.',
        'about.v3.t'        => 'تحویل پایدار',
        'about.v3.d'        => 'کد تمیز، مستندات کامل و پشتیبانی واقعی پس از تحویل.',
        'about.cta'         => 'شروع همکاری با ما',

        'footer.desc'       => 'استودیویی مهندسی-نرم‌افزاری که با ترکیب شبیه‌سازی، برنامه‌نویسی و توسعه وب، ایده‌های پیچیده را به محصولات هوشمند تبدیل می‌کند.',
        'footer.links'      => 'دسترسی سریع',
        'footer.contact'    => 'ارتباط با ما',
        'footer.categories' => 'دسته‌بندی‌ها',
        'footer.rights'     => 'کلیهٔ حقوق برای فیزیو‌الکتریک محفوظ است.',

        'error.404.title' => 'صفحه‌ای یافت نشد',
        'error.404.text'  => 'مشخصاً صفحه‌ای که دنبالش هستید وجود ندارد یا جابه‌جا شده است.',
        'error.404.home'  => 'بازگشت به صفحهٔ اصلی',
        'error.500.title' => 'خطای سرور',
        'error.500.text'  => 'مشکلی پیش آمد. لطفاً بعداً دوباره تلاش کنید.',

        'meta.home'         => 'ایده‌های مهندسی، ساختن راه‌حل‌های هوشمند',
        'meta.projects'     => 'پروژه‌ها | شبیه‌سازی، برنامه‌نویسی و توسعه وب',
        'meta.blog'         => 'بلاگ | مقالات فنی مهندسی و نرم‌افزار',
        'meta.about'        => 'دربارهٔ ما | استودیوی فناوری و مهندسی',
        'meta.contact'      => 'تماس با ما | درخواست پروژه و همکاری',
        'meta.keywords'     => 'فیزیو‌الکتریک, شبیه‌سازی, COMSOL, MATLAB, Python, توسعه وب, مهندسی, هوش مصنوعی',

        // ---------------- Admin (Persian UI) ----------------
        'admin.title'        => 'پنل مدیریت',
        'admin.dashboard'    => 'داشبورد',
        'admin.posts'        => 'مطالب بلاگ',
        'admin.projects'     => 'پروژه‌ها',
        'admin.settings'     => 'تنظیمات سایت',
        'admin.viewSite'     => 'مشاهدهٔ سایت',
        'admin.logout'       => 'خروج',
        'admin.welcome'      => 'خوش آمدید، {name}',
        'admin.stat.posts'   => 'مطالب بلاگ',
        'admin.stat.projects'=> 'پروژه‌ها',
        'admin.stat.published'=> 'منتشرشده',
        'admin.stat.uploads' => 'فایل‌های آپلودشده',
        'admin.recent'       => 'آخرین موارد',
        'admin.quick'        => 'دسترسی سریع',
        'admin.newPost'      => 'مطلب جدید',
        'admin.newProject'   => 'پروژهٔ جدید',
        'admin.edit'         => 'ویرایش',
        'admin.delete'       => 'حذف',
        'admin.save'         => 'ذخیره',
        'admin.cancel'       => 'انصراف',
        'admin.actions'      => 'عملیات',
        'admin.status'       => 'وضعیت',
        'admin.published'    => 'منتشرشده',
        'admin.draft'        => 'پیش‌نویس',
        'admin.date'         => 'تاریخ',
        'admin.category'     => 'دسته',
        'admin.slug'         => 'اسلاگ (URL)',
        'admin.title'        => 'عنوان',
        'admin.image'        => 'تصویر',
        'admin.uploadImage'  => 'آپلود تصویر',
        'admin.currentImage' => 'تصویر فعلی',
        'admin.removeImage'  => 'حذف تصویر',
        'admin.techTags'     => 'تگ‌های فناوری (با ویرگول جدا کنید)',
        'admin.shortDesc'    => 'توضیح کوتاه',
        'admin.content'      => 'محتوا',
        'admin.metaTitle'    => 'عنوان سئو (Title)',
        'admin.metaDesc'     => 'توضیح سئو (Description)',
        'admin.statusField'  => 'وضعیت انتشار',
        'admin.saveChanges'  => 'ذخیرهٔ تغییرات',
        'admin.confirmDelete'=> 'آیا از حذف این مورد مطمئن هستید؟ این عمل قابل بازگشت نیست.',
        'admin.saved'        => 'تغییرات با موفقیت ذخیره شد.',
        'admin.deleted'      => 'مورد با موفقیت حذف شد.',
        'admin.created'      => 'مورد با موفقیت ایجاد شد.',
        'admin.fillAll'      => 'فیلدهای الزامی را تکمیل کنید.',
        'admin.slugTaken'    => 'این اسلاگ قبلاً استفاده شده است؛ اسلاگ دیگری انتخاب کنید.',
        'admin.editPost'     => 'ویرایش مطلب',
        'admin.editProject'  => 'ویرایش پروژه',
        'admin.noRows'       => 'موردی یافت نشد.',
        'admin.perPage'      => 'نمایش',
        'admin.of'           => 'از',

        'admin.set.identity'  => 'هویت سایت',
        'admin.set.contact'   => 'اطلاعات تماس',
        'admin.set.hero'      => 'بخش هیرو (پوش صفحه)',
        'admin.set.footer'    => 'فوتر',
        'admin.set.siteName'  => 'نام سایت',
        'admin.set.telegram'  => 'نام کاربری تلگرام (بدون @)',
        'admin.set.email'     => 'ایمیل تماس',
        'admin.set.phone'     => 'تلفن تماس',
        'admin.set.addressFa' => 'آدرس (فارسی)',
        'admin.set.addressEn' => 'آدرس (انگلیسی)',
        'admin.set.heroBadge' => 'برچسب هیرو',
        'admin.set.heroTitle' => 'عنوان هیرو',
        'admin.set.heroSub'   => 'زیرعنوان هیرو',
        'admin.set.footerDesc'=> 'توضیح فوتر',
        'admin.set.save'      => 'ذخیرهٔ تنظیمات',

        'admin.login.title'   => 'ورود به پنل مدیریت',
        'admin.login.sub'     => 'برای ادامه، حساب کاربری خود را وارد کنید.',
        'admin.login.email'   => 'ایمیل',
        'admin.login.pass'    => 'رمز عبور',
        'admin.login.submit'  => 'ورود',
        'admin.login.invalid' => 'ایمیل یا رمز عبور نادرست است.',
        'admin.login.locked'  => 'تلاش‌های ناموفق زیاد بود. لطفاً {min} دقیقه صبر کنید.',
        'admin.login.empty'   => 'ایمیل و رمز عبور را وارد کنید.',

        'editor.bold'    => 'بولد',
        'editor.italic'  => 'کج',
        'editor.underline'=>'زیرخط',
        'editor.h2'      => 'عنوان ۲',
        'editor.h3'      => 'عنوان ۳',
        'editor.p'       => 'پاراگراف',
        'editor.ul'      => 'لیست نقطه‌ای',
        'editor.ol'      => 'لیست شماره‌ای',
        'editor.quote'   => 'نقل‌قول',
        'editor.code'    => 'کد',
        'editor.link'    => 'لینک',
        'editor.image'   => 'تصویر',
        'editor.unlink'  => 'حذف لینک',
        'editor.clear'   => 'حذف قالب‌بندی',
    ],

    'en' => [
        'lang.name'        => 'English',
        'lang.switch'      => 'FA',

        'nav.home'         => 'Home',
        'nav.projects'     => 'Projects',
        'nav.blog'         => 'Blog',
        'nav.about'        => 'About',
        'nav.contact'      => 'Contact',
        'nav.cta'          => 'Start a Project',

        'hero.scroll'      => 'Scroll',
        'hero.ctaPrimary'  => 'View Projects',
        'hero.ctaSecondary'=> 'Request Collaboration',

        'cap.title'        => 'What We Build',
        'cap.subtitle'     => 'From intelligent software to advanced engineering simulations, we turn complex technical challenges into engineered solutions.',
        'cap.c0.title'     => 'Core Tech & Engineering',
        'cap.c0.desc'      => 'We build robust architectures using modern languages and frameworks including Python, C++, React, and OpenCV for specialized solutions.',
        'cap.c0.link'      => 'Explore Technologies',
        'cap.c1.title'     => 'Engineering Simulations',
        'cap.c1.desc'      => 'Solving electromagnetic, thermal and mechanical problems with COMSOL and MATLAB — from 3-D modeling to parameter optimization.',
        'cap.c1.link'      => 'Simulation Projects',
        'cap.c2.title'     => 'Programming & AI',
        'cap.c2.desc'      => 'Signal processing, machine vision and workflow automation with Python and deep learning; turning raw data into smart decisions.',
        'cap.c2.link'      => 'Programming Projects',
        'cap.c3.title'     => 'Design & Web Development',
        'cap.c3.desc'      => 'Multilingual websites, data dashboards and admin panels with clean architecture, deep SEO and high performance.',
        'cap.c3.link'      => 'Web Projects',

        'home.projects.title'   => 'Selected Projects',
        'home.projects.subtitle'=> 'Explore some of the engineering, software and AI solutions we have developed.',
        'home.projects.viewAll' => 'View All Projects',
        'home.blog.title'       => 'Latest Articles',
        'home.blog.subtitle'    => 'The technical knowledge of the PhysioElectric team — from simulation to multilingual SEO.',
        'home.blog.viewAll'     => 'All Articles',

        'process.title'   => 'How We Work',
        'process.subtitle'=> 'Your project path from an idea to the final product, in four transparent steps.',
        'process.s1.t'    => 'Discovery & Analysis',
        'process.s1.d'    => 'We listen carefully, model the problem and define the exact project scope.',
        'process.s2.t'    => 'Design & Simulation',
        'process.s2.d'    => 'Digital models eliminate risk before build; we pick the best architecture first.',
        'process.s3.t'    => 'Implementation & Testing',
        'process.s3.d'    => 'Clean code, automated tests and step-by-step review with you.',
        'process.s4.t'    => 'Delivery & Support',
        'process.s4.d'    => 'Complete documentation, training and post-launch support.',

        'faq.title'    => 'Frequently Asked Questions',
        'faq.q1'       => 'How is pricing determined?',
        'faq.a1'       => 'Pricing depends on scope, technical complexity and duration. After a free initial session you receive a written technical-financial proposal — no hidden costs.',
        'faq.q2'       => 'Do you take small projects?',
        'faq.a2'       => 'Yes. From a single data-analysis script to a full system, anything inside our expertise gets the same care.',
        'faq.q3'       => 'How long does a project take?',
        'faq.a3'       => 'It depends on the work; simulations usually take 2 to 6 weeks and software projects 4 to 12 weeks. The exact timeline is defined in the proposal.',
        'faq.q4'       => 'Do you use contracts and NDAs?',
        'faq.a4'       => 'Yes. Every project starts with a written contract and, when required, a Non-Disclosure Agreement.',
        'faq.q5'       => 'Is there support after delivery?',
        'faq.a5'       => 'Yes. Every delivery includes technical documentation and a free support period, with long-term support plans available.',

        'contact.title'      => "Let's Talk About Your Project",
        'contact.subtitle'   => 'By phone, email or Telegram — we usually respond within 24 hours.',
        'contact.telegram'   => 'Chat on Telegram',
        'contact.email'      => 'Send an Email',
        'contact.phone'      => 'Phone',
        'contact.address'    => 'Address',
        'contact.worktime'   => 'Saturday to Wednesday, 9 to 17',

        'cta.title'     => 'Want a Project Like This?',
        'cta.subtitle'  => 'Contact our team and let us turn your idea into a practical solution.',
        'cta.telegram'  => 'Order on Telegram',
        'cta.email'     => 'Request via Email',
        'cta.tgMsg'     => 'Hello! I saw the "{title}" project on the PhysioElectric site and would like to request a similar project.',
        'cta.mailSubj'  => 'Project Request: {title}',

        'projects.all'         => 'All Projects',
        'projects.title'       => 'Projects',
        'projects.subtitle'    => 'Selected engineering, software and web work from our team.',
        'projects.view'        => 'View Project',
        'projects.order'       => 'Order This Project',
        'projects.related'     => 'Related Projects',
        'projects.category'    => 'Category',
        'projects.tags'        => 'Technologies',
        'projects.updated'     => 'Updated',
        'projects.notFound'    => 'No project found with this reference.',
        'projects.back'        => 'Back',

        'blog.title'        => 'Blog',
        'blog.subtitle'     => 'Technical articles, tutorials and experiences from the PhysioElectric team.',
        'blog.readMore'     => 'Read More',
        'blog.related'      => 'Related Articles',
        'blog.share'        => 'Share',
        'blog.back'         => 'Back to Blog',
        'blog.minRead'      => 'min read',
        'blog.noPosts'      => 'No articles published yet.',
        'blog.published'    => 'Published on',

        'about.title'       => 'About PhysioElectric',
        'about.subtitle'    => 'We are an engineering-software studio that brings physics, math and code into one team.',
        'about.story.t'     => 'Our Story',
        'about.story.p1'    => 'PhysioElectric was born at the intersection of engineering and programming. We believe the best solutions emerge when the physics of a problem, the mathematics of its model and the code of its implementation think together from day one.',
        'about.story.p2'    => 'Today our team works on three main axes: advanced engineering simulations, custom software development and modern web design. Every project — big or small — is followed with the same precision and transparency.',
        'about.v1.t'        => 'Engineering Precision',
        'about.v1.d'        => 'Every number we deliver comes from a validated model and real data.',
        'about.v2.t'        => 'Full Transparency',
        'about.v2.d'        => 'Progress is measurable and documented at every stage — no surprises.',
        'about.v3.t'        => 'Sustainable Delivery',
        'about.v3.d'        => 'Clean code, complete documentation and real support after delivery.',
        'about.cta'         => 'Start Working With Us',

        'footer.desc'       => 'An engineering-software studio that combines simulation, programming and web development to turn complex ideas into intelligent products.',
        'footer.links'      => 'Quick Links',
        'footer.contact'    => 'Contact Us',
        'footer.categories' => 'Categories',
        'footer.rights'     => 'All rights reserved to PhysioElectric.',

        'error.404.title' => 'Page Not Found',
        'error.404.text'  => 'The page you are looking for does not exist or has been moved.',
        'error.404.home'  => 'Back to Home',
        'error.500.title' => 'Server Error',
        'error.500.text'  => 'Something went wrong. Please try again later.',

        'meta.home'         => 'Engineering Ideas. Building Intelligent Solutions.',
        'meta.projects'     => 'Projects | Simulation, Programming & Web Development',
        'meta.blog'         => 'Blog | Engineering & Software Articles',
        'meta.about'        => 'About Us | Technology & Engineering Studio',
        'meta.contact'      => 'Contact | Project Request & Collaboration',
        'meta.keywords'     => 'PhysioElectric, simulation, COMSOL, MATLAB, Python, web development, engineering, AI',

        // ---------------- Admin (Persian UI; EN fallbacks) ----------------
        'admin.title'        => 'Admin Panel',
        'admin.dashboard'    => 'Dashboard',
        'admin.posts'        => 'Blog Posts',
        'admin.projects'     => 'Projects',
        'admin.settings'     => 'Site Settings',
        'admin.viewSite'     => 'View Site',
        'admin.logout'       => 'Logout',
        'admin.welcome'      => 'Welcome, {name}',
        'admin.stat.posts'   => 'Blog Posts',
        'admin.stat.projects'=> 'Projects',
        'admin.stat.published'=> 'Published',
        'admin.stat.uploads' => 'Uploaded Files',
        'admin.recent'       => 'Recent Items',
        'admin.quick'        => 'Quick Actions',
        'admin.newPost'      => 'New Post',
        'admin.newProject'   => 'New Project',
        'admin.edit'         => 'Edit',
        'admin.delete'       => 'Delete',
        'admin.save'         => 'Save',
        'admin.cancel'       => 'Cancel',
        'admin.actions'      => 'Actions',
        'admin.status'       => 'Status',
        'admin.published'    => 'Published',
        'admin.draft'        => 'Draft',
        'admin.date'         => 'Date',
        'admin.category'     => 'Category',
        'admin.slug'         => 'Slug (URL)',
        'admin.title'        => 'Title',
        'admin.image'        => 'Image',
        'admin.uploadImage'  => 'Upload Image',
        'admin.currentImage' => 'Current image',
        'admin.removeImage'  => 'Remove image',
        'admin.techTags'     => 'Tech tags (comma separated)',
        'admin.shortDesc'    => 'Short description',
        'admin.content'      => 'Content',
        'admin.metaTitle'    => 'SEO Title',
        'admin.metaDesc'     => 'SEO Description',
        'admin.statusField'  => 'Publish status',
        'admin.saveChanges'  => 'Save Changes',
        'admin.confirmDelete'=> 'Are you sure you want to delete this item? This cannot be undone.',
        'admin.saved'        => 'Changes saved successfully.',
        'admin.deleted'      => 'Item deleted successfully.',
        'admin.created'      => 'Item created successfully.',
        'admin.fillAll'      => 'Please fill in all required fields.',
        'admin.slugTaken'    => 'This slug is already in use; pick another one.',
        'admin.editPost'     => 'Edit Post',
        'admin.editProject'  => 'Edit Project',
        'admin.noRows'       => 'Nothing found.',
        'admin.perPage'      => 'Showing',
        'admin.of'           => 'of',

        'admin.set.identity'  => 'Site Identity',
        'admin.set.contact'   => 'Contact Info',
        'admin.set.hero'      => 'Hero Section',
        'admin.set.footer'    => 'Footer',
        'admin.set.siteName'  => 'Site name',
        'admin.set.telegram'  => 'Telegram username (without @)',
        'admin.set.email'     => 'Contact email',
        'admin.set.phone'     => 'Phone',
        'admin.set.addressFa' => 'Address (FA)',
        'admin.set.addressEn' => 'Address (EN)',
        'admin.set.heroBadge' => 'Hero badge',
        'admin.set.heroTitle' => 'Hero title',
        'admin.set.heroSub'   => 'Hero subtitle',
        'admin.set.footerDesc'=> 'Footer description',
        'admin.set.save'      => 'Save Settings',

        'admin.login.title'   => 'Admin Login',
        'admin.login.sub'     => 'Sign in to continue.',
        'admin.login.email'   => 'Email',
        'admin.login.pass'    => 'Password',
        'admin.login.submit'  => 'Sign In',
        'admin.login.invalid' => 'Invalid email or password.',
        'admin.login.locked'  => 'Too many failed attempts. Please wait {min} minutes.',
        'admin.login.empty'   => 'Enter your email and password.',

        'editor.bold'    => 'Bold',
        'editor.italic'  => 'Italic',
        'editor.underline'=>'Underline',
        'editor.h2'      => 'Heading 2',
        'editor.h3'      => 'Heading 3',
        'editor.p'       => 'Paragraph',
        'editor.ul'      => 'Bullet list',
        'editor.ol'      => 'Numbered list',
        'editor.quote'   => 'Quote',
        'editor.code'    => 'Code',
        'editor.link'    => 'Link',
        'editor.image'   => 'Image',
        'editor.unlink'  => 'Remove link',
        'editor.clear'   => 'Clear formatting',
    ],
];
